
# This source entry describes the table:
#   "raw"."public"."Orders_"
#
# It can be referenced with:
#  {{ source('ecommerce', 'orders') }}

version: 2

#sources:
#  - name: v_stg
#    database: DV_PROTOTYPE_DB  # Tell dbt to look for the source in the "raw" database
#    schema: STG # You wouldn't put your source data in public, would you?
#    tables:
#      - name: V_STG_CUSTOMER

models:
  - name: hub_customer
    tests:
      - unique:
          column_name: CUSTOMER_PK
      - unique:
          column_name: CUSTOMERKEY
      - not_null:
          column_name: CUSTOMER_PK
      - not_null:
          column_name: CUSTOMERKEY
      - relationships:
          column_name: CUSTOMER_PK
          to: ref('v_stg_tpch_data')
          field: CUSTOMER_PK
      - relationships:
          column_name: CUSTOMERKEY
          to: ref('v_stg_tpch_data')
          field: CUSTOMERKEY
      - column_type:
          table_name: hub_customer
          column_name: CUSTOMER_PK
          type: BINARY
      - column_type:
          table_name: hub_customer
          column_name: CUSTOMERKEY
          type: NUMBER
  - name: hub_nation
    tests:
      - unique:
          column_name: NATION_PK
      - unique:
          column_name: NATIONKEY
      - not_null:
          column_name: NATION_PK
      - not_null:
          column_name: NATIONKEY
      - column_type:
          table_name: hub_nation
          column_name: NATION_PK
          type: BINARY
      - column_type:
          table_name: hub_nation
          column_name: NATIONKEY
          type: NUMBER
  - name: link_customer_nation
    tests:
      - unique:
          column_name: CUSTOMERKEY_NATION_PK
      - not_null:
          column_name: CUSTOMERKEY_NATION_PK
      - relationships:
          column_name: CUSTOMERKEY_NATION_PK
          to: ref('v_stg_tpch_data')
          field: CUSTOMERKEY_NATION_PK
      - relationships:
          column_name: CUSTOMER_PK
          to: ref('hub_test')
          field: CUSTOMER_PK
      - relationships:
          column_name: CUSTOMER_NATIONKEY_PK
          to: ref('hub_test2')
          field: NATION_PK
  - name: sat_hub_customer
    tests:
      - unique:
          column_name: CUSTOMER_HASHDIFF
      - not_null:
          column_name: CUSTOMER_HASHDIFF
      - relationships:
          column_name: CUSTOMER_HASHDIFF
          to: ref('v_stg_tpch_data')
          field: CUSTOMER_HASHDIFF
      - relationships:
          column_name: CUSTOMER_PK
          to: ref('hub_test')
          field: CUSTOMER_PK
  - name: source_system
    tests:
      - within_date:
          date_column: ORDERDATE
          max_date: TO_DATE('1993-01-02')
