site_name: dbtvault
site_author: Datavault
theme:
    name: 'material'
    custom_dir: 'theme'
    show_sidebar: true
    logo: 'assets/images/logo.png'
    banner: 'assets/images/docs-banner.png'
    favicon: 'assets/images/favicon.ico'
    palette:
      primary: 'black'
      accent: 'indigo'
    highlightjs: true

repo_name: 'Datavault-UK/dbtvault'
repo_url: 'https://github.com/Datavault-UK/dbtvault'

nav:
  - Home: 'index.md'
  - Getting Started: 'gettingstarted.md'
  - Loading the vault:
      - Staging: 'staging.md'
  - Macros: 'macros.md'
  - Licence: 'LICENSE.md'

extra:
  social:
    - type: 'globe'
      link: 'www.data-vault.co.uk'
    - type: 'github'
      link: 'https://github.com/Datavault-UK/'
    - type: 'twitter'
      link: 'https://twitter.com/datavault_uk'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/business-thinking-limited'
    - type: 'facebook'
      link: 'https://www.facebook.com/DataVaultUK/'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      permalink: true
      toc_depth: 1-3

extra_css:
  - 'stylesheets/cube.css'

copyright: dbtvault and docs &copy; Datavault 2019 | dbt is a registered trademark of Fishtown Analytics