site_name: dbtvault
site_author: Datavault
site_dir: 'site'
theme:
    name: 'material'
    custom_dir: 'theme'
    show_sidebar: true
    logo: 'assets/images/logo.png'
    banner: 'assets/images/docs-banner.png'
    favicon: 'assets/images/favicon.ico'
    palette:
      primary: 'black'
      accent: 'indigo'
    highlightjs: true

repo_name: 'Datavault-UK/dbtvault'
repo_url: 'https://github.com/Datavault-UK/dbtvault'

nav:
  - Home: 'index.md'
  - Metadata: 'metadata.md'
  - Walk-through guide:
      - Getting Started: 'walkthrough.md'
      - Staging: 'staging.md'
      - Hubs: 'hubs.md'
      - Links: 'links.md'
      - Satellites: 'satellites.md'
      - T-Links: 't_links.md'
      - Effectivity Satellites: 'eff_sats.md'
  - Worked example:
    - Getting Started: 'workedexample.md'
    - Project setup: 'setup.md'
    - Profiling TPC-H: 'sourceprofile.md'
    - Creating the stage layers: 'stagingdemo.md'
    - Loading the vault: 'loading.md'
  - Macros: 'macros.md'
  - Migration from v0.4 to v0.5: 'migrating.md'
  - Best Practices: 'bestpractices.md'
  - Roadmap: 'roadmap.md'
  - Changelog: 'changelog.md'
  - Contributing: 'contributing.md'
  - Licence: 'LICENSE.md'

extra:
  social:
    - type: 'globe'
      link: 'https://www.data-vault.co.uk'
    - type: 'github'
      link: 'https://github.com/Datavault-UK/'
    - type: 'twitter'
      link: 'https://twitter.com/datavault_uk'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/business-thinking-limited'
    - type: 'facebook'
      link: 'https://www.facebook.com/DataVaultUK/'
  version: 0.5
  req_dbt_version: 0.15.x

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      permalink: true
      toc_depth: 1-3

plugins:
  - search

extra_css:
  - 'stylesheets/extra.css'

copyright: dbtvault and documentation &copy; Business Thinking trading as Datavault 2020 - Data Vault 2.0 is a registered trademark of Dan Linstedt - dbt is a registered trademark of Fishtown Analytics
