site_name: dbtvault
site_author: Datavault
site_dir: 'site'
repo_name: 'Datavault-UK/dbtvault'
repo_url: 'https://github.com/Datavault-UK/dbtvault'

theme:
    name: 'material'
    custom_dir: 'theme'
    show_sidebar: true
    logo: 'assets/images/logo.png'
    banner: 'assets/images/docs-banner.png'
    favicon: 'assets/images/favicon.ico'
    palette:
      primary: 'black'
      accent: 'indigo'
    highlightjs: true


nav:
  - Home: 'index.md'
  - Metadata: 'metadata.md'
  - Walk-through guide:
      - Getting Started: 'walkthrough.md'
      - Staging: 'staging.md'
      - Hubs: 'hubs.md'
      - Links: 'links.md'
      - Satellites: 'satellites.md'
      - Transactional Links: 't_links.md'
      - Effectivity Satellites: 'eff_sats.md'
  - Worked example:
    - Getting Started: 'workedexample.md'
    - Project setup: 'setup.md'
    - Profiling TPC-H: 'sourceprofile.md'
    - Creating the stage layers: 'stagingdemo.md'
    - Loading the vault: 'loading.md'
  - Macros: 'macros.md'
  - Migration Guides:
    - Migrating from v0.4 to v0.5: 'migrating_v0.4_v0.5.md'
  - Best Practices: 'bestpractices.md'
  - Roadmap: 'roadmap.md'
  - Changelog:
    - Stable Releases: 'changelog.md'
    - Beta Releases: 'changelog_beta.md'
  - Contributing: 'contributing.md'
  - Licence: 'LICENSE.md'

extra:
  social:
    - icon: 'fontawesome/solid/globe'
      link: 'https://www.data-vault.co.uk'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/Datavault-UK/'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/datavault_uk'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/business-thinking-limited'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/DataVaultUK/'
  version: 0.5
  req_dbt_version: 0.15.x

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 1-3

plugins:
  - search

extra_css:
  - 'stylesheets/extra.css'

copyright: dbtvault and documentation &copy; Business Thinking trading as Datavault 2020 - Data Vault 2.0 is a registered trademark of Dan Linstedt - dbt is a registered trademark of Fishtown Analytics
