trigger:
  branches:
    include:
      - develop
      - feat/harness-refactor

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Build_environment'
    jobs:
      - job: 'install_dependencies'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - script: pip install pipenv
            displayName: 'Install pipenv'
          - script: pipenv install --dev
            displayName: 'Install Pipenv dependencies'
          - script: |
              curl -sSfo op.zip \
                https://bucket.agilebits.com/cli-private-beta/v2/op_linux_amd64_v2-alpha1.zip \
                && unzip -od /usr/local/bin/ op.zip \
                && rm op.zip
            displayName: "Install 1Password"
          - script: op read op://dbtvault/snowflake/database