trigger:
  batch: true
  branches:
    include:
      - develop
    exclude:
      - feat/*

pool:
  vmImage: ubuntu-latest

variables:
  PIPELINE_BRANCH: $(Build.SourceBranchName)

stages:
  - stage: 'unit_tests'
    displayName: 'Run Unit Tests'
    jobs:
      - job: 'unit_tests_00'
        displayName: 'Run Unit Tests'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-harness-tests -p snowflake
            displayName: "Run harness tests"
          - script: inv run-macro-tests -p snowflake
            displayName: "Run macro tests - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

  - stage: 'integration_tests_snowflake'
    displayName: 'Run Integration Tests (Snowflake)'
    jobs:
      - job: 'staging_01'
        displayName: 'Integration Snowflake Staging'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s staging -p snowflake
            displayName: "Staging - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

  - stage: 'integration_tests_snowflake'
    displayName: 'Run Integration Tests (Snowflake)'
    jobs:
      - job: 'hubs_02'
        displayName: 'Integration Snowflake Hubs'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s hubs -p snowflake
            displayName: "Hubs - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'links_03'
        displayName: 'Integration Snowflake Links'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s links -p snowflake
            displayName: "Links - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'tlinks_04'
        displayName: 'Integration Snowflake TLinks'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s t_links -p snowflake
            displayName: "Transactional Links - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'sats_05'
        displayName: 'Integration Snowflake Sats'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s sats -p snowflake
            displayName: "Satellites - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'sats_with_oos_06'
        displayName: 'Integration Snowflake Sats OOS'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s sats_with_oos -p snowflake
            displayName: "Satellites (Out of Sequence) - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'eff_sats_07'
        displayName: 'Integration Snowflake Eff Sats'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s eff_sats -p snowflake
            displayName: "Effectivity Satellites - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      # Split this further
      - job: 'ma_sats_08'
        displayName: 'Integration Snowflake MA Sats'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s ma_sats -p snowflake
            displayName: "Multi-Active Satellites - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

#      - job: 'ma_sats_1cdk_09'
#        displayName: 'Integration Snowflake MA Sats 1CDK'
#        steps:
#          - task: UsePythonVersion@0
#            inputs:
#              versionSpec: '3.9'
#          - template: templates/install-dependencies-steps.yml
#          - script: inv setup -p snowflake -e pipeline
#            displayName: "Setup harness - Snowflake"
#          - script: inv run-integration-tests -s ma_sats -p snowflake
#            displayName: "Multi-Active Satellites - Snowflake"
#            env:
#              PIPELINE_JOB: $(Agent.JobName)

      - job: 'xts_10'
        displayName: 'Integration Snowflake XT Sats'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s xts -p snowflake
            displayName: "Extended Tracking Satellites - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'bridge_11'
        displayName: 'Integration Snowflake Bridges'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s bridge -p snowflake
            displayName: "Bridges - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'pit_12'
        displayName: 'Integration Snowflake PITs'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s pit -p snowflake
            displayName: "Point In Time - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'cycle_13'
        displayName: 'Integration Snowflake Cycles'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s cycle -p snowflake
            displayName: "Cycles - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)
