trigger:
  batch: true
  branches:
    include:
      - develop
    exclude:
      - feat/*

pool:
  vmImage: ubuntu-latest

variables:
  PIPELINE_BRANCH: $(Build.SourceBranchName)

stages:
  - stage: 'unit_tests'
    displayName: 'Unit Tests'
    jobs:
      - job: 'unit_tests'
        displayName: 'Run Unit Tests'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-dbt "run-operation drop_all_custom_schemas" -p snowflake
            displayName: "Drop all custom schemas"
          - script: inv run-harness-tests -p snowflake
            displayName: "Run harness tests"
          - script: inv run-macro-tests -p snowflake
            displayName: "Run macro tests - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

  - stage: 'integration_tests_snowflake'
    displayName: 'Run Integration Tests (Snowflake)'
    jobs:
      - job: 'staging'
        displayName: 'Staging'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s staging -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'hubs'
        displayName: 'Hubs'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s hubs -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'links'
        displayName: 'Links'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s links -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'tlinks'
        displayName: 'TLinks'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s t_links -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'sats_main'
        displayName: 'Sats Main'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s sats --subtype main -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'sats_cycles'
        displayName: 'Sats Cycles'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s sats --subtype cycles -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'sats_pm'
        displayName: 'Sats PM'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s sats --subtype pm -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'sats_rm'
        displayName: 'Sats RM'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s sats --subtype rank -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'eff_sats_main'
        displayName: 'Eff Sats Main'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s eff_sats --subtype main -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'eff_sats_auto'
        displayName: 'Eff Sats Auto'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s eff_sats --subtype auto -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'eff_sats_multi_part'
        displayName: 'Eff Sats Multi Part'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s eff_sats --subtype multi_part -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'eff_sats_mat'
        displayName: 'Eff Sats Mat'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s eff_sats --subtype mat -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'eff_sats_closed'
        displayName: 'Eff Sats Closed'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s eff_sats --subtype closed -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'ma_sats_1cdk'
        displayName: 'MA Sats 1CDK'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s ma_sats --subtype 1cdk -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'ma_sats_1cdk_cyc'
        displayName: 'MA Sats 1CDK-Cycles'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s ma_sats --subtype 1cdk_cycles -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'ma_sats_2cdk'
        displayName: 'MA Sats 2CDK'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s ma_sats --subtype 2cdk -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'ma_sats_2cdk_cyc'
        displayName: 'MA Sats 2CDK-Cycles'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s ma_sats --subtype 2cdk_cycles -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'ma_sats_pm'
        displayName: 'MA Sats PM'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s ma_sats --subtype pm -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'cycle'
        displayName: 'Cycles'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness"
          - script: inv run-integration-tests -s cycle -p snowflake
            displayName: "Run feature files"
            env:
              PIPELINE_JOB: $(Agent.JobName)
