trigger:
  batch: true
  branches:
    include:
      - develop
    exclude:
      - feat/*

pool:
  vmImage: ubuntu-latest

variables:
  PIPELINE_BRANCH: $(Build.SourceBranchName)

stages:
  - stage: 'unit_tests'
    displayName: 'Run Unit Tests'
    jobs:
      - job: 'unit_tests_00'
        displayName: 'Run Unit Tests'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-harness-tests -p snowflake
            displayName: "Run harness tests"
          - script: inv run-macro-tests -p snowflake
            displayName: "Run macro tests - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

  - stage: 'integration_tests_snowflake'
    displayName: 'Run Integration Tests (Snowflake)'
    jobs:
      - job: 'hubs_links_01'
        displayName: 'Integration Snowflake Hubs Links'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s hubs,links -p snowflake
            displayName: "Run Integration tests - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'sats_02'
        displayName: 'Integration Snowflake Satellites'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s sats -p snowflake
            displayName: "Run Integration tests - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)