trigger:
  branches:
    include:
      - develop
      - feat/harness-refactor

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'unit_tests'
    displayName: 'Run Unit Tests'
    jobs:
      - job: 'run_harness_tests'
        displayName: 'Run Test Harness Unit Tests'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: python -m inv setup -p snowflake
          - script: python -m inv run-harness-tests -p snowflake

      - job: 'run_snowflake_tests'
        displayName: 'Run Snowflake Macro Unit Tests'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: python -m inv setup -p snowflake
          - script: python -m inv run-macro-tests -p snowflake

