trigger:
  batch: true
  branches:
    include:
      - develop
    exclude:
      - feat/*

pool:
  vmImage: ubuntu-latest

variables:
  PIPELINE_BRANCH: $(Build.SourceBranchName)

stages:
  - stage: 'unit_tests'
    displayName: 'Run Unit Tests'
    jobs:
      - job: 'unit_tests_00'
        displayName: 'Run Unit Tests'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-harness-tests -p snowflake
            displayName: "Run harness tests"
          - script: inv run-macro-tests -p snowflake
            displayName: "Run macro tests - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

  - stage: 'integration_tests_snowflake'
    displayName: 'Run Integration Tests (Snowflake)'
    jobs:
      - job: 'staging_01'
        displayName: 'Integration Snowflake Staging'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s staging -p snowflake
            displayName: "Staging - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'hubs_02'
        displayName: 'Integration Snowflake Hubs'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s hubs -p snowflake
            displayName: "Hubs - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'links_03'
        displayName: 'Integration Snowflake Links'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s links -p snowflake
            displayName: "Links - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'tlinks_04'
        displayName: 'Integration Snowflake TLinks'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s t_links -p snowflake
            displayName: "Transactional Links - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'sats_main_05'
        displayName: 'Integration Snowflake Sats Main'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s sats --subtype main -p snowflake
            displayName: "Satellites (Main) - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'sats_pms_06'
        displayName: 'Integration Snowflake Sats PM Standard'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s sats --subtype pm_standard -p snowflake
            displayName: "Satellites (PM Standard) - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'sats_pmr_07'
        displayName: 'Integration Snowflake Sats PM Ranges'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s sats --subtype pm_ranges -p snowflake
            displayName: "Satellites (PM Ranges) - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'sats_rm_08'
        displayName: 'Integration Snowflake Sats RM'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s sats --subtype rank -p snowflake
            displayName: "Satellites (RM Ranges) - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'sats_with_oos_09'
        displayName: 'Integration Snowflake Sats OOS'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s sats_with_oos -p snowflake
            displayName: "Satellites (Out of Sequence) - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'eff_sats_10'
        displayName: 'Integration Snowflake Eff Sats'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s eff_sats -p snowflake
            displayName: "Effectivity Satellites - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'ma_sats_1cdk_11'
        displayName: 'Integration Snowflake MA Sats 1CDK'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s ma_sats --subtype 1cdk -p snowflake
            displayName: "Multi-Active Satellites (1CDK) - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'ma_sats_1cdk_cyc_12'
        displayName: 'Integration Snowflake MA Sats 1CDK-Cycles'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s ma_sats --subtype 1cdk_cycles -p snowflake
            displayName: "Multi-Active Satellites (1CDK-Cycles) - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'ma_sats_2cdk_13'
        displayName: 'Integration Snowflake MA Sats 2CDK'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s ma_sats --subtype 2cdk -p snowflake
            displayName: "Multi-Active Satellites (2CDK) - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'ma_sats_2cdk_cyc_14'
        displayName: 'Integration Snowflake MA Sats 2CDK-Cycles'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s ma_sats --subtype 2cdk_cycles -p snowflake
            displayName: "Multi-Active Satellites (2CDK-Cycles) - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'ma_sats_pm_15'
        displayName: 'Integration Snowflake MA Sats PM'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s ma_sats --subtype pm -p snowflake
            displayName: "Multi-Active Satellites (PM) - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'xts_16'
        displayName: 'Integration Snowflake XT Sats'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s xts -p snowflake
            displayName: "Extended Tracking Satellites - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'bridge_17'
        displayName: 'Integration Snowflake Bridges'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s bridge -p snowflake
            displayName: "Bridges - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'pit_18'
        displayName: 'Integration Snowflake PITs'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s pit -p snowflake
            displayName: "Point In Time - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)

      - job: 'cycle_19'
        displayName: 'Integration Snowflake Cycles'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - template: templates/install-dependencies-steps.yml
          - script: inv setup -p snowflake -e pipeline
            displayName: "Setup harness - Snowflake"
          - script: inv run-integration-tests -s cycle -p snowflake
            displayName: "Cycles - Snowflake"
            env:
              PIPELINE_JOB: $(Agent.JobName)
