version: 2.1


orbs:
  python: 'circleci/python@0.3.0'
  slack: circleci/slack@3.4.2

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dbtvault-dev-{{ arch }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - v1-dbtvault-dev-{{ arch }}-{{ .Branch }}
            - v1-dbtvault-dev-
      - run:
          name: Install pip
          command: |
            sudo apt update
            sudo apt install -y python-pip python-dev tar gzip
      - run:
          name: Install pipenv and dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: v1-dbtvault-dev-{{ arch }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - /.circleci/.cache
      - run:
          command: cd tests/dbtvault_test/ ; pipenv run dbt deps
  test:
    executor: python/default
    steps:
      - run:
          command: pipenv run python -m pytest ./tests/unit
      - slack/status:
          fail_only: false
          mentions: 'URXTX0XEZ'

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          context: dbtvault_snowflake_test
          filters:
            branches:
              only: master
      - test:
          context: dbtvault_snowflake_test
          requires:
            - build
          filters:
            branches:
              only: master