version: 2.1

orbs:
  python: 'circleci/python@0.3.0'

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: dbt deps
      - run:
          command: python -m unittest discover tests/unit -v
          

workflows:
  main:
    jobs:
      - build-and-test:
          context: dbtvault_snowflake_test
