version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: pip install -r requirements
      - run:
          command: cd tests/dbtvault_test/ ; dbt deps
      - run:
          command: python -m unittest discover -s /home/alex/PycharmProjects/dbtvault-dev/tests/unit -t /home/alex/PycharmProjects/dbtvault-dev/tests/unit

workflows:
  main:
    jobs:
      - build-and-test:
          context: dbtvault_snowflake_test
