version: 2.1


orbs:
  python: 'circleci/python@0.3.0'
  slack: circleci/slack@3.4.2
  secrethub: secrethub/cli@1.0.1

jobs:
  build-and-test:
    executor: python/default
    parallelism: 15
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dbtvault-dev-{{ arch }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - v1-dbtvault-dev-{{ arch }}-{{ .Branch }}
            - v1-dbtvault-dev-
      - run:
          name: Install pip
          command: |
            sudo apt update
            sudo apt install -y python-pip python-dev tar gzip
      - run:
          name: Install pipenv and dependencies
          command: |
            sudo -H pip install pipenv
            pipenv install --dev
            pipenv install 
      - save_cache:
          key: v1-dbtvault-dev-{{ arch }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - /.circleci/.cache
      - secrethub/install
      - run:
          name: Install dbt dependencies in test project
          command: TARGET=snowflake pipenv run inv run-dbt -u circleci -t snowflake -p test -d 'deps' -e secrethub_circleci.env
      - run:
          name: Run snowflake macro tests
          command: |
            circleci tests glob tests/unit/*/test_*.py | circleci tests split > /tmp/macro-tests-to-run
            TARGET=snowflake pipenv run inv macro-tests -t snowflake -u circleci -e secrethub_circleci.env
      - run:
          name: Run snowflake integration tests
          command: |
            circleci tests glob tests/features/*/*.feature | circleci tests split > /tmp/feature-tests-to-run
            TARGET=snowflake pipenv run inv integration-tests -t snowflake -u circleci -e secrethub_circleci.env
      - slack/status:
          fail_only: false
          mentions: 'URXTX0XEZ'
      - store_test_results:
          path: test_results/integration_tests
      - store_test_results:
          path: test_results/macro_tests
      - store_artifacts:
          path: test_results/integration_tests
      - store_artifacts:
          path: test_results/macro_tests

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master