version: 2.1

orbs:
  python: 'circleci/python@0.3.0'

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: cd tests/dbtvault_test/ ; dbt deps
      - run:
          command: python -m unittest discover -s /home/alex/PycharmProjects/dbtvault-dev/tests/unit -t /home/alex/PycharmProjects/dbtvault-dev/tests/unit

workflows:
  main:
    jobs:
      - build-and-test:
          context: dbtvault_snowflake_test
