version: 2.1

orbs:
  python: 'circleci/python@0.3.0'

jobs:
  build-and-test:
    executor: python/default
    parallelism: 4
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: cd tests/dbtvault_test/ ; dbt deps
      - run:
          command: circleci tests glob "tests/unit/**/test*.py" | circleci tests split > tests_to_run.txt
      - run:
          command: python -m unittest $(cat ./tests/tests_to_run.txt)

      

workflows:
  main:
    jobs:
      - build-and-test:
          context: dbtvault_snowflake_test
