version: 2.1

orbs:
  python: circleci/python:latest
  
jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: | 
            sudo pip install pipenv
            pipenv instal

workflows:
  main:
    jobs:
      - build-and-test
