site_name: dbtvault
theme:
    name: 'material'
    custom_dir: 'theme'
    logo: 'assets/images/logo.png'
    banner: 'assets/images/docs-banner.png'
    favicon: 'assets/images/favicon.ico'
    palette:
      primary: 'black'
      accent: 'indigo'
    highlightjs: true

repo_name: 'Datavault-UK/dbtvault'
repo_url: 'https://github.com/Datavault-UK/dbtvault'

nav:
  - Home: 'index.md'
  - Getting Started: 'gettingstarted.md'
  - Macros: 'macros.md'
  - Table types:
      - Hubs: 'table-types/hubs.md'
      - Links: 'table-types/links.md'
      - Satellites: 'table-types/satellites.md'

extra:
  social:
    - type: 'globe'
      link: 'www.data-vault.co.uk'
    - type: 'github'
      link: 'https://github.com/Datavault-UK/'
    - type: 'twitter'
      link: 'https://twitter.com/datavault_uk'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/business-thinking-limited'
    - type: 'facebook'
      link: 'https://www.facebook.com/DataVaultUK/'

markdown_extensions:
  - codehilite
  - admonition

extra_css:
  - 'stylesheets/cube.css'