name: 'dbtvault_test'
version: '0.7.3'
require-dbt-version: [">=0.18.0", "<0.20.0"]
config-version: 2
profile: dbtvault

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

vars:
  max_date: TO_DATE("9999-12-31")

models:
  dbtvault_test:
    unit:
      +schema: "{{ env_var('SNOWFLAKE_DB_USER') }}{{ '_' ~ env_var('CIRCLE_BRANCH', '') | replace('-','_') | replace('.','_') if env_var('CIRCLE_BRANCH', '') }}{{ '_' ~ env_var('CIRCLE_JOB',\
        \ '') if env_var('CIRCLE_JOB', '') }}{{ '_' ~ env_var('CIRCLE_NODE_INDEX', '') if env_var('CIRCLE_NODE_INDEX', '') }}"
      tables:
        hub:
          +materialized: incremental
        link:
          +materialized: incremental
    feature:
      +schema: "{{ env_var('SNOWFLAKE_DB_USER') }}{{ '_' ~ env_var('CIRCLE_BRANCH', '') | replace('-','_') | replace('.','_') if env_var('CIRCLE_BRANCH', '') }}{{ '_' ~ env_var('CIRCLE_JOB',\
        \ '') if env_var('CIRCLE_JOB', '') }}{{ '_' ~ env_var('CIRCLE_NODE_INDEX', '') if env_var('CIRCLE_NODE_INDEX', '') }}"


seeds:
  +schema: "{{ env_var('SNOWFLAKE_DB_USER') }}{{ '_' ~ env_var('CIRCLE_BRANCH', '') | replace('-','_') | replace('.','_') if env_var('CIRCLE_BRANCH', '') }}{{ '_' ~ env_var('CIRCLE_JOB', '')\
    \ if env_var('CIRCLE_JOB', '') }}{{ '_' ~ env_var('CIRCLE_NODE_INDEX', '') if env_var('CIRCLE_NODE_INDEX', '') }}"
  +quote_columns: true
  dbtvault_test:
    raw_source:
      +column_types:
        CUSTOMER_PK: BINARY(16)
        BOOKING_FK: BINARY(16)
        ORDER_FK: BINARY(16)
        LOADDATE: DATE
    raw_source_2:
      +column_types:
        CUSTOMER_PK: BINARY(16)
        BOOKING_FK: BINARY(16)
        ORDER_FK: BINARY(16)
        LOADDATE: DATE