name: 'dbtTest'
version: '1.0'

profile: 'my-snowflake-db'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
    vars:
        date: TO_DATE('1992-01-08')
        history_date: TO_DATE('1992-01-08')



