analysis-paths:
- analysis
clean-targets:
- target
- dbt_modules
data-paths:
- data
macro-paths:
- macros
models:
  snowflake_demo:
    feature_sql_files:
      enabled: false
      materialized: incremental
      tags: feature
    hub_sat_link_load:
      enabled: true
      materialized: incremental
      tags: history
    source_creation:
      enabled: true
      materialized: incremental
      tags: history
    stg:
      enabled: true
      materialized: view
      tags: history
  vars:
    date: TO_DATE('1992-01-08')
    history_date: TO_DATE('1992-01-08')
name: snowflakeDemo
profile: my-snowflake-db
source-paths:
- models
target-path: target
test-paths:
- tests
version: '1.0'
