analysis-paths:
- analysis
clean-targets:
- target
- dbt_modules
data-paths:
- data
macro-paths:
- macros
models:
  snowflake_demo:
    feature_sql_files:
      enabled: false
      materialized: incremental
    hub_sat_link_load:
      schema: "VLT"
      enabled: true
      materialized: incremental
    source_creation:
      enabled: true
      materialized: incremental
    star_schema:
      schema: STAR
      enabled: true
      materialized: view
    stg:
      schema: STG
      enabled: true
      materialized: view
  vars:
    date: TO_DATE('1992-01-01')
    history_date: TO_DATE('1992-01-01')
name: snowflakeDemo
profile: my-snowflake-db
source-paths:
- models
target-path: target
test-paths:
- tests
version: '1.0'
